/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Permission = 'READ' | 'READ-WRITE';

export const Permission = {
    READ: 'READ' as Permission,
    READWRITE: 'READ-WRITE' as Permission
};