/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiProperty } from '@nestjs/swagger';
export class BabyPointsResponse {
    @ApiProperty({
        type: Number,
        example: 10,
    })
    points: number;

    @ApiProperty({
        type: String,
        example: '64cce29c-e1ec-4a45-be53-bdbfb6ff167d',
    })
    babyId: string;

}