/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiProperty } from '@nestjs/swagger';
import { Gender } from '../enums/gender.enum';
import { Permission } from './models';

export class BabyProfileResponse {
    @ApiProperty({
        type: String,
        example: '59d35eef-bb61-4e05-bc2f-27e006fc81dd',
    })
    id: string;

    @ApiProperty({
        type: String,
        example: "Pride's new baby",
    })
    name: string;

    @ApiProperty({
        enum: Gender,
    })
    gender: Gender;

    @ApiProperty({
        type: String,
        example: '2023-01-04'
    })
    DOB: Date;

    @ApiProperty({
        type: String,
        example: {},
    })
    picture: string;

    @ApiProperty({
        type: String,
        example: 'Mother',
    })
    relationshipWithUser: string;


    @ApiProperty({
        enum: Permission,
    })
    permission: Permission
}