/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class BabyGrowthRecordRequest {
    @ApiProperty({
        type: String,
        example: 'ce92a0d1-f33a-4208-aeea-e811022376d1',
    })
    id?: string;

    @ApiProperty({
        type: String,
        example: '64cce29c-e1ec-4a45-be53-bdbfb6ff167d',
    })
    babyId: string;

    @ApiProperty({
        type: Number,
        format: 'int16',
        example: 10,
    })
    weight: number;

    @ApiProperty({
        type: Number,
        format: 'int16',
        example: 30,
    })
    height: number;

    @ApiProperty({
        type: Number,
        format: 'double',
        example: 10,
    })
    headCircumference: number;

    @ApiProperty({
        type: String,
        example: '2023-04-23',
    })
    date: Date;
}