/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiProperty } from '@nestjs/swagger';
import { Gender } from '../enums/gender.enum';

export class BabyRequest {
    @ApiProperty({
        type: String,
        example: 'Parent',
    })
    relationshipWithUser: string;

    @ApiProperty({
        type: String,
        example: 'Mark',
    })
    name: string;

    @ApiProperty({
        enum: Gender,
    })
    gender: Gender;

    @ApiProperty({
        type: String,
        example: 'base46 image string',
    })
    picture: string;

    @ApiProperty({
        type: String,
        example: '2023/01/05',
    })
    DOB: string;

    @ApiProperty({
        type: Number,
        format: 'double',
        example: 1.5,
    })
    weightAtBirth: number;

    @ApiProperty({
        type: Number,
        format: 'double',
        example: 30,
    })
    heightAtBirth: number;

    @ApiProperty({
        type: Number,
        format: 'double',
        example: 10,
    })
    headCircumferenceAtBirth: number;

    @ApiProperty({
        type: String,
        description: 'You are a',
        example: 'mother',
        enum: ['Mother', 'Father', 'Guardian'],
    })
    relationship: string;

    UserId?: string;
}