/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class ChangeParentProfileRequest {
    @ApiProperty({
        type: 'string',
        example: 'FILE',
    })
    profilePicture: string;

    @ApiProperty({
        type: 'string',
        example: 'email@parent.com',
    })
    email: string;

    @ApiProperty({
        type: 'string',
        example: 'password1',
    })
    oldPassword: string;

    @ApiProperty({
        type: 'string',
        example: 'password1',
    })
    newPassword: string;
}