/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class ChangePasswordRequest {
    @ApiProperty({
        type: 'string',
        example: '55e751c3-7a75-48f6-9309-7b114d01c573',
    })
    id?: string;
    @ApiProperty({
        type: 'string',
        example: '123',
    })
    oldPassword?: string;
    @ApiProperty({
        type: 'string',
        example: '1234',
    })
    newPassword?: string;
}