/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiProperty } from '@nestjs/swagger';
import { Permission } from '../enums/permission.enum';

export class ChildPermission {
    @ApiProperty({
        type: 'string',
        example: '59d35eef-bb61-4e05-bc2f-27e006fc81dd',
    })
    id: string;

    @ApiProperty({ type: Permission })
    permission: Permission;
}