/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class ImmunizationTimelineResponse {
    @ApiProperty({
        example: 6,
        type: Number,
    })
    week: number;

    @ApiProperty({
        example: '6 months',
        type: String,
    })
    age: string;

    @ApiProperty({
        example: 'BCG',
        type: String,
    })
    vaccine: string;

    @ApiProperty({
        example: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
        molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
        numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
        optio, eaque rerum! Provident similique accusantium nemo autem`,
        type: String,
    })
    vaccineDescription: string;

    @ApiProperty({
        example: true,
        type: Boolean,
    })
    isGovernment: boolean;

    @ApiProperty({
        example: true,
        type: Boolean,
    })
    isOptional: boolean;
}