/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApiProperty } from '@nestjs/swagger';
import { ChildPermission } from './childPermission';
import { Permission } from './models';

export class LoginResponse {
    @ApiProperty({
        type: 'string',
        example: 'pride',
    })
    name: string;
    @ApiProperty({
        type: 'string',
        example: '1ccfd5d1-dbe6-4871-9953-d9a7845cd9ea1ccfd5d1-dbe6-4871-9953-d9a7845cd9ea',
    })
    jwt: string;

    @ApiProperty({
        type: 'boolean',
        example: false,
    })
    isVerified: boolean;
}

export class AuthPermissions {
    @ApiProperty({
        type: 'string',
        example: '1ccfd5d1-dbe6-4871-9953-d9a7845cd9ea',
    })
    id: string;

    @ApiProperty({
        type: Permission
    })
    permission: Permission;

    constructor(id: string, permission: Permission) {
        this.id = id;
        this.permission = permission;
    }
}