/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class LoginRequest {
    @ApiProperty({
        type: 'string',
        example: 'parent@parent.com',
    })
    email: string;

    @ApiProperty({
        type: 'string',
        example: 'password123',
    })
    password: string;
}