/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class MilestoneTopic {
    @ApiProperty({
        example: 6,
        type: Number,
    })
    week: number;

    @ApiProperty({
        example: 'Startles to loud sounds',
        type: String,
    })
    topic: string;

    @ApiProperty({
        example: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
        molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
        numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
        optio, eaque rerum! Provident similique accusantium nemo autem`,
        type: String,
    })
    content: string;
}

export class MilestoneResponse {
    @ApiProperty({
        example: 'Cognitive',
        type: String,
    })
    subject: string;

    @ApiProperty({
        example: [
            {
                id: '59d35eef-bb61-4e05-bc2f-27e006fc81dd',
                week: 6,
                topic: 'Startles to loud sounds',
                content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem',
            }
        ],
        type: [MilestoneTopic],
    })
    topics: MilestoneTopic[];
}

