/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class ParentSignUpRequest {
    @ApiProperty({
        type: 'string',
        example: 'parent@example.com',
    })
    email: string;

    @ApiProperty({
        type: 'string',
        example: 'password123',
    })
    password: string;

    @ApiProperty({
        type: 'string',
        example: 'Pride',
    })
    name: string;

    @ApiProperty({
        type: 'integer',
        format: 'int32',
        example: 28,
    })
    age: number;

    @ApiProperty({
        type: 'boolean',
    })
    subscribeToMarketing: boolean;
}
export namespace ParentSignUpRequest {
    export type RelationshipEnum = 'Mother' | 'Father' | 'Guardian';
    export const RelationshipEnum = {
        Mother: 'Mother' as RelationshipEnum,
        Father: 'Father' as RelationshipEnum,
        Guardian: 'Guardian' as RelationshipEnum
    };
}