/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class ResetPasswordStep2Request {
    @ApiProperty({
        example: 'b022a96c-bcd4-4ffc-9d5b-a0af1e869a6f',
        type: 'string',
    })
    verificationToken?: string;
}