/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class ResetPasswordStep1Request {
    @ApiProperty({
        example: 'email@parent.com',
        type: 'string',
    })
    email: string;

    @ApiProperty({
        example: 'password',
        type: 'string',
    })
    newPassword: string;
}