/**
 * Beba
 * Beba app
 *
 * OpenAPI spec version: 1.0.11
 * Contact: bebahealthapp@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiProperty } from "@nestjs/swagger";

export class ToastrResponse {
    @ApiProperty({ type: 'string', example: 'Any message to the UI' })
    message: string;

    @ApiProperty({
        type: 'string',
        description: 'message type',
        example: 'warning',
        enum: ['success', 'warning', 'error'],
    })
    type: 'success' | 'warning' | 'error';
}
export namespace ToastrResponse {
    export type TypeEnum = 'success' | 'warning' | 'error';
    export const TypeEnum = {
        Success: 'success' as TypeEnum,
        Warning: 'warning' as TypeEnum,
        Error: 'error' as TypeEnum
    };
}